### ISSUE TITLE
fetch: https://bsdstore.ru/src_10.3/mirror.html: Not Found

### ISSUE THREAD

**Issue by trombik** [cbsd/cbsd#121]
I am trying cbsd but the default repo is not working.

```
root@server1:/usr/local/cbsd # pkg info | grep cbsd
cbsd-11.0.6_1                  Yet another FreeBSD Jail and Bhyve Management Utility
```

```
cbsd@server1> repo action=get sources=src
REPO:https://bsdstore.ru
fetch: https://bsdstore.ru/src_10.3/mirror.html: Not Found
fetch: https://bsdstore.ru/src_10.3/src.txz: Not Found
Not found: https://bsdstore.ru/src_10.3/src.txz
/usr/local/jails/tools/repo: icontinue: not found
fetch: https://bsdstore.ru/src_10.3/src.txz.md5: Not Found
Not found: https://bsdstore.ru/src_10.3/src.txz.md5
No sources found
```

**Comment by trombik** [comment]
```
cbsd@server1> repo action=ping
Check for repository: https://bsdstore.ru ...Online
```

**Comment by olevole** [comment]
Builds for 10x bases is disabled due to lack of resource: no servers for build and no hosting ;-(
At the moment i've build and put to repos only 11/amd64 and 12/amd64 (aka HEAD/Current), because I use them

**Comment by trombik** [comment]
would you explain how to create a repo or the format of the mirror.html? is there any reason that the official ftp sites cannot be used?

**Comment by olevole** [comment]
as far as i know,  official freebsd repo does not archive of sources, so this is reason why not fetched from official ftp/http. If you need sources, it can obtain via

cbsd srcup
cbsd srcup ver=10.2
cbsd srcup ver=11 stable=1

in this case, you get souces from official FreeBSD svn (or git)

sources needet only to build bases. You can fetch bases by

cbsd repo action=get sources=base

and unlike sources, in this case you get base.txz from official FreeBSD ftp/http,  because they exist

**Comment by trombik** [comment]
ftp.freebsd.org does not but [ftp-archive.freebsd.org](http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/amd64/) keeps old releases. is this not "official enough"?

**Comment by olevole** [comment]
Hmm. Perhaps. But I see that there is no new releases (e.g 10.1, 10.2, 10.3, 11.0). Looks like it is just graveyard for **old** releases only, stuff from End-of-Life version.

I have inattentively looked at your first message and thought that you have problems with obtaining base. So, to obtain sources, the best way is use
~~~
cbsd srcup
~~~

command, if you want to build/prepare bases by himself. 

I will leave this issue in open state, so may be
~~~
repo sources=src
~~~

can be adopted for any sources (e.g. git archive, instead of clone)

**Comment by trombik** [comment]
thanks for the advice. I will look into it. the primary motivation is that, your environment should always be built, or obtained, from the authoritative source. if it's binaries, it should be obtained from the official FTP site. if it's the src, it should be checked out from the CVS repository, or downloaded from the FTP site, and the binaries should be built from the src.

if the FreeBSD project provided users with some kind of a redicrecter, like ubuntu and other distributions do, the `mirror.html` would not be necessary, i guess.

anyway, there are alternatives to achieve my requirement. if `cbsd` would be able to handle various sources in the future, that will definitely be great.

cheers,

**Comment by olevole** [comment]
@trombik to prevent using non-official repo, just change fbsdrepo to '1' via

~~~
cbsd initenv-tui
~~~

- this forced CBSD to use only FreeBSD official ftp/http to fetching **base** 

I disable 'cbsd repo action=get sources=src' in next CBSD release to not confuse users.

mirror.html was necessary for me in the past, when i have central servers and few CDN-like static mirror with the resources. At the moment all resources hoster in one.

But mirror.html is good for me to make automatically select mirror by GEOIP and on-the-fly, when or if I find the additional server for statics content

**Comment by olevole** [comment]
Close issue, cleanup. I hope someday there will be resources for builds all the acyual freebsd versions
