### ISSUE TITLE
Аuthentication error

### ISSUE THREAD

**Issue by MathAnalyz** [cbsd/cbsd#135]
Hello! Error occurs when i run the command "repo action=ping". Result of command to the screenshot.  What's the matter? I use Vmware Workstation Player. 
![default](https://cloud.githubusercontent.com/assets/10303023/23091358/b0225ab8-f5e6-11e6-9731-958cd1ed333d.PNG)

**Comment by olevole** [comment]
Hmm, looks like your system not have ca_root_nss - root certificate bundle. Can you try install it and repeat?

~~~
pkg install security/ca_root_nss 
~~~

On the other hand, I probably should not use SSL for ping - i change this soon.

PS: repo functionality now is off because I do not have the resources to maintain it ;-(. 
I update only base.txz for FreeBSD 11 amd64 and FreeBSD 12 amd64 (aka HEAD/CURRENT), but for use it not necessary for repo command: CBSD downloads them automatically when required

Thanks!

**Comment by MathAnalyz** [comment]
I try and command was executed! Thanks!
