### ISSUE TITLE
pci_passthru_args

### ISSUE THREAD

**Issue by will666** [cbsd/cbsd#172]
Hi,

I'm looking for using **pci_passthru_args**, how do we proceed? I saw the table **bhyveppt** in the sqlite  database, but it's empty. I did not see nothing about it in the documentation.

Thank you in advance.

**Comment by olevole** [comment]
Hi.

I'm not sure pass-thru in CBSD finished ;-) For this reason it still not documented. 
Nevertheless, I began work on this. You can try to use

cbsd bhyve-ppt 

command after booting hoster with corresponding records in /boot/loader.conf:

a) vmm should be loaded via /boot/loader.conf, not after booting system (kldload)
b) you must have pptdevs in /boot/loader.conf ( see https://wiki.freebsd.org/bhyve/pci_passthru ), e.g: pptdevs="5/1/0"

If all you, you can see devices via:

~~~
cbsd bhyve-ppt mode=list
~~~

and try to apply it:
~~~
cbsd bhyve-ppt mode=attach ppt=<ppt> jname=
~~~

but i never test this because I do not have the right equipment ;-)

**Comment by will666** [comment]
I didn't try the command `cbsd bhyve-ppt` yet, but I'm about to do so.
I've done the configuration and used pptdevs in the past, i just wanted to know the "CBSD way" of doing PCI passthrough.
Thank you for your help, i'll get back to you after some tests.

**Comment by will666** [comment]
I just tried the command and it works like a charm, great feature!
Perhaps it would be good to detach the ppt automatically in case of VM deletion - if a VM was deleted while ppt attached, the ppt device will remain unavailable.
Thank you for all your hard work.

**Comment by olevole** [comment]
Wow, this works, Great!  Thanks for testing ;-)

> Perhaps it would be good to detach the ppt automatically in case of VM deletion

It looks reasonable to me. I've return this Issue to open state as reminder to fix it

**Comment by olevole** [comment]
done with https://github.com/cbsd/cbsd/commit/91e1833c12bec742d55af18289992ca86f7e0293
Will be available in next CBSD release: 11.1.0

Thx!

**Comment by will666** [comment]
Great! Thank you again for your time and your hard work. I'm using **CBSD** on a production server and it works pretty good for me, i run around 30 jails and 2 bhyve vms on the same host with ZFS.
I'm also keeping an eye on **ClonOS**, I really like jails as containers and I really love _FreeBSD_.

**Comment by olevole** [comment]
@will666 It's very nice that the project is useful for someone. Feedback/comments and ideas are welcome!
