### ISSUE TITLE
dhclient command not possible inside vnet jail

### ISSUE THREAD

**Issue by sharky1337** [cbsd/cbsd#192]
Hello, 

I tried to follow the tutorial.

https://www.bsdstore.ru/en/cbsd_vnet.html

But with the default settings I'm not able to use dhclient. 

It results in:

Can't find free bpf: No such file or directory

This workaround fixes the problem.

add path 'bpf*' unhide

to the /etc/defaults/devfs.rules, later did a /etc/rc.d/devfs restart
and got it work.

This is how now looks the devfsrules_jail section on devfs.rules

 Devices usually found in a jail.
[devfsrules_jail=4]
add include $devfsrules_hide_all
add include $devfsrules_unhide_basic
add include $devfsrules_unhide_login
add path zfs unhide
## add path 'bpf*' unhide

I don't know if you want to add it to the documentation or do you want to add it when installing cbsd.

Thank you !

**Comment by olevole** [comment]
Hi!

Yeah, some notes exist in doc:
~~~
Also, if you want to get a jail itself an IP address automatically (via DHCP), you would write a separate section devfs.rules, in which you need to open bpf(4)-device ( unhide bpf*), and set this devfs rule number to vnet-jail (via cbsd jconfig jname=XXXX)
~~~

- you can unhide bpf  ( exactly what you did ) 
or
- via `cbsd jconfig` or `cbsd jset` choose devfs_ruleset to non-existent value, e.g.: '99'

Last solution only for trusted (e.g - it is your jail) environment, since it unhide all devices.
Another way : choose profile 'trusted' in `cbsd jconstruct-tui` menu (from CBSD 11.1.2)

But I've agreed with you: documentation is a very weak place in the project. I will leave this issue until I add more information about which you wrote. Thanks!

**Comment by olevole** [comment]
https://github.com/cbsd/cbsd-wwwdoc/commit/c4069ad6b5bc4d1202a8e89f1a2244b6226fb86a
