### ISSUE TITLE
Sending wrong argument to jexec in jcreate.subr

### ISSUE THREAD

**Issue by sweco-secfha** [cbsd/cbsd#197]
In jcreate.subr all executions of jexec looks like `jexec jname=$jname` but jexec expects `jexec $jname` so I had to modify jcreate.subr to work.
I'm on FreeBSD 11.1.

**Comment by olevole** [comment]
Oops, it seems that this bug appeared in one of the latest versions of the CBSD, when I added PATH before post/hook's jexec.

`jexec jname=$jname`

This is correct execution for _~cbsd/sudoexec/jexec_ script, not for system _/usr/sbin/jexec_ 

Each script with **#!/usr/local/bin/cbsd** shebang try to execute script from CBSD hier via custom PATH. But in latest releases I've back PATH to system for some reason.

Correct way to fix is add '/usr/local/bin/cbsd' before jexec in this place, due to 'cbsd jexec' can apply rctl/nice/setfib settings for execution.

I've fix this soon as I get to the normal keyboard  ;-)   Thanks you for contribution!

**Comment by olevole** [comment]
Can you fetch fixes via
~~~
fetch -o /usr/local/cbsd/jcreate.subr https://raw.githubusercontent.com/cbsd/cbsd/master/jcreate.subr
~~~
+ re-run:
~~~
cbsd initenv
~~~

And check this ?

**Comment by olevole** [comment]
**upd**: correct myself: we do not need to reset PATH for jexec, revert it back and remove PATH redefining.

Reseting of PATH should remain only when the master scripts are executed.

**Comment by sweco-secfha** [comment]
Thank you, for your great work!
I can confirm that this fixed the issue. :)

**Comment by olevole** [comment]
commited in ports tree, 11.1.7
