### ISSUE TITLE
Possible comparison with other jail systems?

### ISSUE THREAD

**Issue by priyadarshan** [cbsd/cbsd#224]
I like cbsd very much, and I would like to point it to other people (for example, in similar threads: https://www.reddit.com/r/freebsd/comments/7ex8bw/opinion_jail_utility_cbsd_vs_ezjail_vs_iocage/), but I find it difficult to explain why it is better than other similar tools.
Would it be possible to add a section i the README that carries a simple comparison with iocage, ezjail, etc.?

**Comment by olevole** [comment]
Hello! I think this comparison can be made by a person from outside if he works the same time with all available and relevant management systems. 

I do not think it's a good idea to have a comparison with other projects on the project page ;-) First, this opinion can be biased. Usually in the comparison authors of one software write, always the best solution is their own. For example, take a look comparison from IXSystem (commercial companies who selling FreeNAS appliance): FreeNAS vs Nas4Free (free non-commercial community project):

http://www.freenas.org/freenas-vs-nas4free/

Similar advertising from the commercial company on the own sites - it's a shame, i think ;)

Secondly, this information should be constantly checked - this means that it is necessary to monitor all other solution constantly. Otherwise, it may turn out that we are spreading false information.

In addition, I am not an expert in any other project (I used many years ago ezjail only).

Most of the highlights (including project goals, to which the project is confidently moving) is described on the main page: https://www.bsdstore.ru/en/about.html

And finally I strongly doubt that my project is better than any other) They are slightly different.

It's very good when people who benefited from the project, can write or tell the stories what they liked in the project (without: USE CBSD!!! CBSD BESST!! ;-) ..".  For example, @mekanix in the past - a regular  CBSD user ;-) , today - a full member of the project soon plans to acquaint the public with the project closer and share their experience and thoughts about the project at FOSDEM'18:  https://twitter.com/meka_floss/status/937981809568239616

**Comment by priyadarshan** [comment]
Thank you for the thoughtful comment, they are wise words, I wish there would be more developers like this.

There are quite a few FreeBSD users that would benefit from an educated comparison table, like one can find on WikiPedia and such. I am just a happy user of CBSD, I can't really put together a comparison, simply because I do not use other tools (beside sometimes raw jails).

I hope one day somebody will write such post somewhere, for the benefits of all new FreeBSD users.

Thank you again for CBSD.

**Comment by mekanix** [comment]
To me, it's impossible to write non-biased review because once you choose a jail manager, that's the software you know, and you don't know the rest. If time allows, I would like to write a review of CBSD vs EZJails, as he's using EZJails exclusively, so we could do something like a BSD battle :o)

**Comment by priyadarshan** [comment]
As a new jail user looking for tool choices, I would not mind to read even biased reviews, as long as they state that. Biased would be better than nothing at all. I am looking forward to your writing.

**Comment by olevole** [comment]
I recently read this interesting link http://erdgeist.org/posts/2017/dont-piss-in-my-beer.html  and It seems that the ezjail author was driving completely decided to move away from the project. At least, I do not see active development of ezjail. On the other hand, this may ezjail perfectly and it does not require support at the moment.

In addition, at the moment there are no other solutions except CBSD (or I do not know about them), which work with jail and bhyve simultaneously. We can compare

CBSD **vs** ezjail  ( as jail manager )
CBSD **vs** qjail   ( as jail manager )
CBSD **vs** iocage  (as jail manager )
CBSD **vs** vm-bhyve ( as bhyve manager )
CBSD **vs** bhyve-rc ( as bhyve manager )
CBSD **vs** iohyve ( as bhyve manager)

We can compare only this:

CBSD **vs** "ezjail+qjail+iocage+vm-bhyve+bhyve-rc+iohyve .."

Haha, just kidding;-)

Also, except TUI, CBSD have WEB UI ( ClonOS ), so someday we can compare CBSD+UI vs { Triton,Opennebula, virsh, virt-manager, VBOX, Proxmox, OpenStack, etc.. }

**Comment by priyadarshan** [comment]
Thank you for sharing that link, I am sorry for ezjail developer, I always liked the feeling of his tool.

Thank you also for ClonOS, I did not know about it, it is quite remarkable!

**Comment by olevole** [comment]
Ok, so, I close this issue. The CBSD project has a problem in the form of good documentation and articles about it (especially in English) and I think it's best to focus on this. As for the comparison, it's unlikely that someone will be able to do it without bias, it's not for the official site;) Thank you for the feedback!

PS: By the way, we launched (Thanks to TildaCenter and @mekanix )  a mailing list for CBSD-related talks. Similar issues can now be discussed there)

**Comment by Dieken** [comment]
FYI, CBSD isn't listed:  https://appjail.readthedocs.io/en/latest/compare/

**Comment by mergar** [comment]
> FYI, CBSD isn't listed: https://appjail.readthedocs.io/en/latest/compare/

@Dieken This is not our page, it belongs to https://github.com/DtxdF/AppJail/ project. Pages like these are not easy to keep unbiased ;-)
