### ISSUE TITLE
cpio: … Cannot extract through symlink ….

### ISSUE THREAD

**Issue by Juronski** [cbsd/cbsd#287]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.1-RELEASE-p9 FreeBSD 11.1-RELEASE-p9

CBSD version ( cbsd version ): 11.1.18

Hi,

After upgrading the system from FreeBSD 10.3 to 11.1 I tried to upgrade the jails with “cbsd jupgrade” but I get “cpio: … Cannot extract through symlink …. ” errors

this is an example of a error-line

`cpio: .//bin/rmail: Cannot extract through symlink /usr/jails/jails-data/jailname-data/bin/rmail`

“/usr/jails/jails-data” is the symlink to "/tank/jails-data"

Never had this before eg when upgrading from 10.0 to 10.1 and to 10.3. I’m not sure if this is a CBSD issue and I hope someone has a solution.

Thank you in advance.
J.

**Comment by olevole** [comment]
Hi, your environments are configured in the baserw mode?
'''cbsd jls display=jname,ver,baserw'''
?

**Comment by Juronski** [comment]
Hi, 
Yes, environment is configured in the baserw=1 mode.
"jailname       11.1   1"
J.

**Comment by olevole** [comment]
Hmm. I suggest you use at the moment default FreeBSD tools: freebsd-update ( https://www.bsdstore.ru/en/11.1.x/wf_jupgrade_ssi.html#freebsd-upgrade ). I'm not sure I can fix it quickly. And maybe it does not make sense anymore:

because at the moment @mekanix works on a new and more universal script for jail updating ( formally, the new script will use freebsd-update for FreeBSD or hbsd-update for HardenedBSD .. to update files).

Also, I plan to make support in the near future  for FreeBSD-in-packages update method. E.g, I update my servers through 'pkg': https://pastebin.com/wRQd1NHr

It seems that this is the best and fastest method of updating FreeBSD bases.

So, most likely, we will no longer develop and maintain the old 'jupgrade' script.

**Comment by Juronski** [comment]
Ok. Thank you. Always used the `cbsd jupgrade` script. Now I use  `freebsd-update` for `jailbase`-dir and then `sudo cbsd jset jname=namejail ver=11.1`, restarted the jail and went on with `pkg-static` etc to upgrade the jailsystem. Flawless . Great!!

**Comment by olevole** [comment]
You're welcome! We will soon update the documentation on the jupgrade in accordance with the latest changes. I will leave this Issue open as a reminder.

**Comment by mekanix** [comment]
Just a heads up, baseupdate updates all jails and it fails if there's no update (I saw it too late, code was in the release). As `baseupdate` is not stable, we decided to keep it as a hidden feature until it's mature.

**Comment by olevole** [comment]
@Juronski 
> “/usr/jails/jails-data” is the symlink to "/tank/jails-data"

^^ it was a very useful remark. We use cpio from current directory. In your case this was not the real path, so I've add realpath(1) in these places. Your situation only occurs when directories use symbolic links. Thanks for reports, fixed via https://github.com/cbsd/cbsd/commit/5a541d8c3b9b1e8b3d60a38b40b3bec23d707f76
