### ISSUE TITLE
Package check reports missing files

### ISSUE THREAD

**Issue by goligo** [cbsd/cbsd#370]
FreeBSD version ( uname -a ): 11.2
CBSD version ( cbsd version ): 12.0.3

After installing 12.0.3 using pkg upgrade and running initenv, the daily security report shows this:

Checking for packages with mismatched checksums:
cbsd-12.0.3: missing file /usr/local/cbsd/bin/cbsdsftp
cbsd-12.0.3: missing file /usr/local/cbsd/bin/cbsdsftp6
cbsd-12.0.3: missing file /usr/local/cbsd/bin/cbsdssh
cbsd-12.0.3: missing file /usr/local/cbsd/bin/cbsdssh6
cbsd-12.0.3: missing file /usr/local/cbsd/bin/cfetch
cbsd-12.0.3: missing file /usr/local/cbsd/lib/simplexml/simplexml.o
cbsd-12.0.3: missing file /usr/local/cbsd/misc/cbsd_dot
cbsd-12.0.3: missing file /usr/local/cbsd/misc/cbsd_fwatch
cbsd-12.0.3: missing file /usr/local/cbsd/misc/cbsdlogtail
cbsd-12.0.3: missing file /usr/local/cbsd/misc/cbsdtee
cbsd-12.0.3: missing file /usr/local/cbsd/misc/chk_arp_byip
cbsd-12.0.3: missing file /usr/local/cbsd/misc/conv2human
cbsd-12.0.3: missing file /usr/local/cbsd/misc/daemon
cbsd-12.0.3: missing file /usr/local/cbsd/misc/dump_cpu_topology
cbsd-12.0.3: missing file /usr/local/cbsd/misc/dump_iscsi_discovery
cbsd-12.0.3: missing file /usr/local/cbsd/misc/elf_tables
cbsd-12.0.3: missing file /usr/local/cbsd/misc/popcnttest
cbsd-12.0.3: missing file /usr/local/cbsd/misc/pwcrypt
cbsd-12.0.3: missing file /usr/local/cbsd/misc/resolv
cbsd-12.0.3: missing file /usr/local/cbsd/misc/sqlcli
cbsd-12.0.3: missing file /usr/local/cbsd/misc/src/dump_cpu_topology.o
cbsd-12.0.3: missing file /usr/local/cbsd/misc/src/dump_iscsi_discovery.o
cbsd-12.0.3: missing file /usr/local/cbsd/sbin/netmask
cbsd-12.0.3: missing file /usr/local/cbsd/tools/imghelper
cbsd-12.0.3: missing file /usr/local/cbsd/tools/racct-bhyve-statsd
cbsd-12.0.3: missing file /usr/local/cbsd/tools/racct-hoster-statsd
cbsd-12.0.3: missing file /usr/local/cbsd/tools/racct-jail-statsd
cbsd-12.0.3: missing file /usr/local/cbsd/tools/select_jail

Looks like initenv does move these files to the cbsd home directory, so when pkg checks whether all files are intact, they are detected as missing. Maybe initenv could rather create links to the original files than moving them?

**Comment by olevole** [comment]
these files are listed in the manifest, however they were deleted via

make -C /usr/local/cbsd clean

these files are not involved in the process, its just artifact from 'cbsd initenv' when CBSD recompiled and and copies files into workdir.

current behavior is a legacy from an old idea, when there were plans to make secure updates.
In the near future I plan to do work on supporting multiple CBSD workdir, like virtualenv or something like.

Where each workdir can be isolated with personal basedir for jail or personal dataset and quoatas.

So this issue will be fixed by the new architecture, where all scripts and binaries in /usr/local/cbsd, whereas workdir will contain only

jails
jails-data
jails-system
 
and var/db directory

one environment at the same time will be the default (as now - the only), whereas with the rest of the working directories you can work by specifying the environment, eg:

env cbsd_workdir=/ssd cbsd jls
env cbsd_workdir=/nfs cbsd jconstruct-tui
env cbsd_workdir=/mnt/ceph bstart windows
...

Thus, this problem will be fixed :-) I suggest to wait and be patient. Or do not execute

make clean

In /usr/local/cbsd directory

**Comment by olevole** [comment]
although it seems that initenv does this operation on its own. Anyway, at the moment it is an architectural legacy and requires refactoring, which I wrote about above :(

**Comment by goligo** [comment]
Thanks for your fast response. The checksum checks for packages have been introduced to prevent accidental or harmful modification of package binaries. By moving these files out of the location where they have been installed, the cbsd binaries are no longer covered by these checks. I will be patient ;-)
