### ISSUE TITLE
Need import script from existing jail's to current jail's CBSD logic

### ISSUE THREAD

**Issue by click0** [cbsd/cbsd#388]
Need import script from existing jail's to current jail's CBSD logic.

uname -a : `FreeBSD 11.0-STABLE #0 r311150: Tue Jan  3 04:47:48 EET 2017`

My config /etc/jail.conf:

```
allow.raw_sockets = 1;
exec.clean;
exec.system_user = "root";
exec.jail_user = "root";
exec.start = "/bin/sh /etc/rc";
exec.stop = "/bin/sh /etc/rc.shutdown";
exec.consolelog = "/var/log/jail_${name}_console.log";
mount.devfs;
mount.fstab = "/etc/fstab.$name";
allow.mount;
allow.set_hostname = 0;
allow.sysvipc = 0;
path = "/jails/${name}";

web {
    host.hostname = "web.VPS.domain.com";
    ip4.addr = "re0|10.0.0.21/24";
    ip4.addr += "lo0|127.0.1.1/8";
    ip6.addr += "re0|2001:311:143:65::21:1/64";
    ip6.addr += "re0|2001:311:143:65:8693:2a27:a219:6e05/64";
    ip6.addr += "re0|2001:311:143:65:80ca:f097:df2e:e343/64";
    ip6.addr += "re0|2001:311:143:65:dca9:45be:0ca8:f598/64";
    ip6.addr += "re0|2001:311:143:65:4dc2:29f4:246a:3954/64";
    ip6.addr += "lo0|::10.0.0.21/128";
    allow.sysvipc = 1;
    mount.procfs;
    devfs_ruleset = 7;
#    path = "/jails/billing-test";
}

```

**Comment by olevole** [comment]
I created a separate repository for related scripts (  https://github.com/cbsd/cbsd_useful_stuff ), since the third-party scripts from the community related to the project definitely growing. I hope someday we will be able to see the migrator from classic jail to CBSD ). Eg one of CBSD user wrote a small script and howto about migrate from ezjail to CBSD. Maybe it will be interesting for you: https://www.bsdstore.ru/en/12.0.x/ezjail2cbsd_ssi.html

As for the similar functionality in the CBSD core/base, I decided that this is bad for several reasons:

1) it is difficult because there are still no tools for parsing jail.conf in FreeBSD base. for example, this is one of the reasons why ezjail development was stopped[1]
2) CBSD still develop and migrator code needs for maintainer. because I personally and my tasks do not use classic jail, I have little interest in this ( but I will be glad if someone helps, as in the case of ezjail2cbsd)
3) not only ezjail exist. if we add one, it is reasonable to write migration scripts for all projects. which is impossible with the number of developers CBSD. But if we look at the root of the problem, we should have a universal container format (like OVF for vm). OCI can help? In this case, you should not ask each project to create a migration script from thousands of other projects. You must ask for a universal format support.

For these reasons, I will close this task because it does not relate to the CBSD problem. but I do not rule out that we will ever see third-party scripts. 
--
[*1] http://erdgeist.org/posts/2017/dont-piss-in-my-beer.html
       https://lists.freebsd.org/pipermail/freebsd-jail/2013-March/002160.html

^^ interesting information from the  ezjail author about jail.con and shell-based projects like CBSD
