### ISSUE TITLE
Bhyve in console mode

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#476]
Is there a chance to get (back?) pure console mode for bhyve vm? I know there were discussions regarding some disadvantages, but do they apply for FreeBSD guests?

Console mode for at least FreeBSD guests would be great, but Linux is appreciated too.

**Comment by olevole** [comment]
I am not opposed to returning the bhyveload method for the BSD guest. Unfortunately, I am now very busy with more priority tasks to do this work myself

**Comment by uropro** [comment]
Is it possible to hack something to make the console accessible? like adding options to bhyve_options or bhyve_flags in cbsd bconstruct-tui?

**Comment by mekanix** [comment]
@oleg if you have time to explain how it used to work, I'll find time over the weekend to implement it.

**Comment by olevole** [comment]
> @oleg if you have time to explain how it used to work, I'll find time over the weekend to implement it.

without a very deep dive I cannot answer what is the best way to realize this again) if I found it correctly, then support was removed not far from this commit: https://github.com/cbsd/cbsd/commit/cc03ee6de

maybe we should add 'custom boot script'  (together with EFI/CSM) or custom settings for 'bhyverun script'  with which, instead of running a regular CBSD script /usr/local/cbsd/share/bhyverun.sh user can implement your own script to run bhyve ( through the configuration file or arguments, he will be able to get all the necessary settings )

**Comment by olevole** [comment]
most likely 'custom/alternative' bhyverun script is the best and flexible choice - for example, we can already specify an alternative binary file insteaf of /usr/sbin/bhyve ( bhyve_cmd variable/params ). it also gives us the opportunity to launch an alternative 'bhyve' build (with DEBUG, with experimental patches like p9fs and so on) without hack CBSD code

**Comment by uropro** [comment]
Oleg, your proposal sounds like a very flexible solution, it would allow me to do whatever I like with the my beloved console... :-)

**Comment by uropro** [comment]
Hi Oleg, is there a chance that you could implement this "alternative/custom" bhyverun script in cbsd? That would be great, I am still no fan of VNC...

**Comment by olevole** [comment]
>  I am still no fan of VNC...

I was hoping that a few years could change that. But I see that in the future you may never be a VNC fan, ha ha.

I added the ability to use an alternative script ( bhyverun_wrapper options ):

Also the CBSD has an example of how it can be processed: https://github.com/cbsd/cbsd/blob/develop/share/examples/bhyve/bhyverun.sh

To use custom script, you must respect the original parameters/args, since CBSD runs the script with the same keys.

This is short demo: https://youtu.be/4SbrjKOWJU0

I suppose this also applies to https://github.com/cbsd/cbsd/issues/323

**Comment by uropro** [comment]
Hi Oleg
Great news, I am looking forward to test and use it!!! Many thanks already, also for the documentation and video!!!
You're right, I am getting too old to be flexible enough and getting a VNC fan ... ;-)
Best regards, -Urs
