### ISSUE TITLE
bhyve PCI Passthrough

### ISSUE THREAD

**Issue by hereisamr** [cbsd/cbsd#498]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 12.1

CBSD version ( cbsd version ): CBSD v12

Hello,
I am trying to use bhyve PCI Passthrough and device has disappeared from the host and appeared in the guest and I have assigned to it a static IP, but unfortunately I can not ping it.

Any further steps I should make or I miss?

Thanks for such amazing tool

**Comment by olevole** [comment]
@hereisamr Hi!

Thanks for the report (and feedback). Unfortunately, this kind of problem lies beyond the capabilities of the CBSD. I can recommend you try to reproduce the problem without any third-party wrapper ( like vm-bhyve/CBSD/...), e.g from command line or via /usr/share/examples/bhyve/vmrun.sh

Third-party wrappers like a CBSD and vm-bhyve -  is just a generator of arguments for the command line to start the hypervisor, whereas your problem most likely lies below. 

You can see the arguments with which the hypervisor is launched under the control of CBSD:
```
% ps axfww | grep bhyve
```

If your device works successfully without a wrapper, then the problem is in the CBSD and the wrong arguments. In this case, I would like you to re-open this issue (and write the arguments with which your device works). Otherwise - I would recommend starting a discussion in ML:  https://lists.freebsd.org/mailman/listinfo/freebsd-virtualization

In my practice, not all devices worked. Basically, I had no problems using SR-IOV (Virtual Function, network device): https://www.bsdstore.ru/en/12.1.x/wf_bhyveppt_ssi.html#sriov

Please let me know if you have any new information!
