### ISSUE TITLE
Daily security run reports missing files

### ISSUE THREAD

**Issue by Ingo-Sys** [cbsd/cbsd#513]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64

CBSD version ( cbsd version ): 
12.1.15

-------------
The following is in the mail:

Checking for packages with mismatched checksums:
cbsd-12.1.15: missing file /usr/local/cbsd/lib/simplexml/simplexml.o
cbsd-12.1.15: missing file /usr/local/cbsd/misc/src/dump_cpu_topology.o
cbsd-12.1.15: missing file /usr/local/cbsd/misc/src/dump_iscsi_discovery.o

--------------
A list of other files with missmatched checksums has also been present. 
I ran pkg check -r to get rid of those.

Upgrade has been done from previous versions of CBSD. cbsd initenv has been run after every upgrade.

I have used touch to create the missing files above and the ran pkg check -s. It doesn't report missing files after that.
The daily report hasn't run since I have done the above.

Is there a better way of resolving this issue?

**Comment by olevole** [comment]
This problem is more related to /usr/ports/sysutils/cbsd port, not a codebase. but since the port is also maintained by me - I will try not to forget to fix it in the next release ;-)

Need to switch auto-generated pkg-list to static file, without *.o files ( object files should not go into the port/package ). Thanks for report.

**Comment by olevole** [comment]
12.1.16 committed today into ports tree without .o files in plist. Starting from this version you shouldn't see these problems. Thx for report.
