### ISSUE TITLE
Jail skeletons always create etcupdate conflicts

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#557]
The skeletons presents in `~/share` don't take into account future jail updates.
For example, the header of `~/share/FreeBSD-jail-vnet-skel/etc/group` is:
`# $FreeBSD: head/etc/group 336525 2018-07-19 23:55:29Z ian $`
So, when a jail, created from this skeleton, is updated using `cbsd etcupdate` - there is **always** a conflict on `/etc/group`.
For v.11.4 we suppose to have here a header:
`# $FreeBSD: releng/11.4/etc/group 359448 2020-03-30 17:11:21Z brooks $`
...and for v.12.1 - a header:
`# $FreeBSD: releng/12.1/etc/group 336525 2018-07-19 23:55:29Z ian $`

A solution could be template-based skeletons where file headers are replaced by version-dependent headers on jails creation.

**Comment by olevole** [comment]
This error occurs because the CBSD has only one reference version of the skel files.
The correct fix should look like the presence of skeletons of files for all supported versions, e.g:
share/FreeBSD-jail-vnet-skel-11.2
share/FreeBSD-jail-vnet-skel-11.3
share/FreeBSD-jail-vnet-skel-12.0
share/FreeBSD-jail-vnet-skel-12.1
share/FreeBSD-jail-vnet-skel-12.2
share/FreeBSD-jail-vnet-skel-13.0
share/FreeBSD-jail-vnet-skel-14
...

The main reason for the difference is the presence of RCS string ( **$FreeBSD$ tags** )

Last year, FreeBSD moved to the use of Git, and this line/tags was abolished. 

I think, starting with the 13.0 version, such problems should not arise. As for old versions, this problem will take themselves with the time itself =) as the bases are obsolete.
