### ISSUE TITLE
Installing CBSD vhd and VM in different zpool

### ISSUE THREAD

**Issue by JEAholding** [cbsd/cbsd#567]
FreeBSD version ( uname -a ): 
FreeBSD 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64
CBSD version ( cbsd version ): 
13.0.1

=============================================================================================

So I have been playing with CBSD for over 1.5 month+ now (relatively new) and now I come to request (can't find an answer in the documentation) or on config --help, so maybe you can guide me in correct direction. I have zpool_1 as the main (OS BOOT gateway) and have 2+ extra zpool with independent drives all on raid 0 same node/server. 

My question is how can I make the installation of my bhyve VM install on another zpool ? Currently, I have (3) zpool list, and any bconstruct install I do always INSTALL on main zpool1 = THE BOOT zpool. 

I tested with putting the 
env workdir="/zpool2/usr/jails" /usr/local/cbsd/sudoexec/initenv .....  But when I do bconstruct-tui creates on zpool1 = THE BOOT zpool. 

I tested..... Saving CBSD bin to the /zpool2/bin/cbsd and executing shell through that zpool mount BUT always installs bconstruct on zpool1. 

What am I missing? 

Do I need to add some config to add extra zpools somewhere in cbsd files? Is there any way to install VM on a separate zpool that is not the zpool_boot_os and if so how do I go about doing this? 

Thanks in advance...

**Comment by olevole** [comment]
Independent working directories (environments) in CBSD concept - this is the correct way to use multiple pools.
When you initialize the working directory with an alternate working directory, if you want to use it, then always specify the working directory when using the commands:
```
env workdir=/zpool2/usr/jails cbsd bconstruct-tui
env workdir=/zpool2/usr/jails cbsd bls
env workdir=/zpool2/usr/jails cbsd bstart
env workdir=/zpool2/usr/jails cbsd bcreate jname=c1 vm_ram=4g vm_cpus=2 vm_os_type=linux vm_os_profile="cloud-CentOS-7-x86_64" ci_ip4_addr=10.0.0.110 ip4_addr=10.0.0.110 runasap=1 imgsize=6g
..
```

This is not very convenient from the point of view of the command line, because by default (via the rc.conf file) you can have only one working directory, the main.

For this reason, such complex installations suggest the presence of another/additional layer (for example, beanstalkd + API): https://www.bsdstore.ru/en/cbsd_api_ssi.html

I think in large and complex infrastructures, this should become the main method of working with virtual environments:
at the moment the project is looking for an easy way to manage complex installations (beyond the localhost and only the command line). And it seems using CBSDfile is the correct proof of concept. E.g. CBSDfile for Gitlab installation (for CBSD **13.0.2** which was recently released):

https://github.com/cbsd/cbsdfile-recipes/tree/master/jail/gitlab

Instead of 
```
cbsd bcreate jname=c1 vm_ram=4g vm_cpus=2 vm_os_type=linux vm_os_profile="cloud-CentOS-7-x86_64" ci_ip4_addr=10.0.0.110 ip4_addr=10.0.0.110 runasap=1 imgsize=6g
```

you can use alternative vagrant-like style form with CBSDfile:
```
bhyve_c1()
{
        vm_ram="4g"
        vm_cpus="2"
        imgsize="6g"
        vm_os_type=linux
        vm_os_profile="cloud-CentOS-7-x86_64"
        runasap=1
        ssh_wait=1
}
```
This file will work the same via `cbsd up', `cbsd blogin', `cbsd destroy` (same for jail), ... on the local machine and if you add (CLOUD_KEY= CLOUD_URL= variables to your/private API) for remote host.

Most likely, in the next version we will add **tags** that can regulate the selection for creating the target node and the working directory on it, e.g:

```
bhyve_vm1()
{
        vm_ram="1g"
        vm_cpus="1"
        imgsize="20g"
        tags="pool:zpool2,external_ip:true"..
}
```

However,  in any case requires an extra layer above the CBSD, which should remain a low-level framework for simple operations with environments.

**Comment by JEAholding** [comment]
A lot more clear on the hierarchy and config of the program ..... 

Everything you wrote A++ tested already, everything working beautifully actually!!! 

I like the management through the different env workdir path A LOT, very straight to the point...  

After you told me about the cbsd rc.conf limitation, I was thinking maybe a cronjob on startup to start the VM on a different zpool in case of reboot or a secondary solution simple rc.d might work for me..... Having said that, I think the cbsd config tags you mention are not bad to have, will also give beanstalkd a try... 

Thank you so much for all your help!!!
