### ISSUE TITLE
jstatus does not work properly for bhyve

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#597]
https://github.com/cbsd/cbsd/blob/937069b94a11f9ee50cd55e70211fddb7cefe320/tools/expose#L105-L106

for existing bhyve domains it returns 0, so they are not displayed in show_all_expose output

**Comment by olevole** [comment]
For bhyve we need 'bstatus' but I cannot understand why I was chosen 'find' + 'status' to build valid envinronments list instead of 'SELECT jname FROM ..'. Most likely this is due to the case when the container may not be registered (unregistered/sharedfs). Simplified the logic and the status became unnecessary. Thanks!
