### ISSUE TITLE
blogin does not work after bexport/bimport

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#603]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 13.0-RELEASE-p1

CBSD version ( cbsd version ): 13.0.8

```
% sudo cbsd blogin edx
 *** VM booted in VNC mode. ***
For attach VM console, use: vncviewer :5905
Do you want to attach into UEFI console anyway?
[yes(1) or no(0)]
```

---

direct ssh-ing with cbsd root key works well though

**Comment by olevole** [comment]
This is because we do not have persistent storage for cloud-init settings except ascii file in form of ~cbsd/jails-system/<env>/rc.conf_<env>. Assuming this only works when initializing the virtual machine.

Most likely, we will need to expand the SQL settings and store CI-related information there. 

As a temporary workaround, we will copy the ci-related settings through the ~cbsd/jails-system/<env>/rc.conf_<env>.orig file

There can also be a problem here when the login key is used from the host system (default behavior) and the image is imported to another server. Probably worth giving a "warning" just in case.
