### ISSUE TITLE
Jails NAT inside private network

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#634]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 13.0-RELEASE-p4

CBSD version ( cbsd version ): 13.0.15

I use VNET jails on a server, placed in a corporate network. The server has vmx0 interface with IP address 172.17.14.12/24, VNET jails are using the network 10.192.7.128/25, local gateways for jails are configured in 10.192.7.0/25. The network infrastructure is out of my control, so I must use NAT on my server to get jails communicating with the world. I use `cbsd expose` to configure inbound NAT, and I activated 'Configure NAT for RFC1918 Network' in `cbsd initenv` for outbound traffic. Everything works fine when my jails communicate with Internet hosts. There is a problem communicating with another private networks though.
For example, the outbound traffic from my jail with IP 10.192.7.130 to a host in another private network 10.21.101.20 is not NATed as the NAT hide rules are configured as follows:
```
nat on vmx0 inet from 10.0.0.0/8 to ! 10.0.0.0/8 -> 172.17.14.12
nat on vmx0 inet from 192.168.0.0/16 to ! 192.168.0.0/16 -> 172.17.14.12
```
I think that the problem can be fixed by using only the network configured for jails as 'nodeippool' in NAT rules and not all RFC1918 Networks. Or even better, use the list of configured jail's IP here and not the whole network.

As for me, I temporary fixed the problem replacing 10.0.0.0/8 by 10.192.7.0/24 in initenv.subr.

**Comment by olevole** [comment]
it seems to me that the list of IP addresses is not a good idea, because CBSD may not know the addresses in containers (e.g. vnet jails, bhyve VM, + aliases on environment interface which are configured by users without CBSD).

maybe we can turn default rules into file-based templates, e.g.:

_~cbsd/etc/pfctl.conf.tpl:_
```
nat on <extnic> inet from XXX to ! XXX -> $nodeip
...
```

because an automation suitable for one case can break another. With template, CBSD solves almost nothing, just does

**Comment by olevole** [comment]
I have long wanted to make it possible to include the custom rules, because I cannot predict all cases. also, it is necessary to regulate redirects rules for expose. Most likely there should be several templates, e.g.:

nat.rules.tpl
rdr.rules.tpl
..

which will generate chunks of files

But the user must write a common file with the inclusions of these chunks in the correct order.

This is relevant for `pf` but not sure about `ipfw` (and `ipfilter` ;)

**Comment by olevole** [comment]
Since 13.1.23 version we can play with the 'cbsd_nat_skip_natip_network'+'cbsd_nat_networks' parameters in the **~cbsd/etc/cbsd-pf.conf** file to achieve the desired result, e.g.:
```
cat > ~cbsd/etc/cbsd-pf.conf <<EOF
cbsd_nat_networks="10.192.7.0/24"
cbsd_nat_skip_natip_network=0
EOF
```

**Comment by Peter2121** [comment]
YESSSSSS!!!!! :)
