### ISSUE TITLE
jconfig hostname update does not work on running jail

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#649]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 13-R

CBSD version ( cbsd version ): 13.0.16

how to reproduce
cbsd jconfig jname=<...>, then set hostname, commit
the hostname does not change, and the change is reset.

expected behavior:
hostname is set immediately, or after jail restart.

**Comment by olevole** [comment]
Hmm, `jstart` set hostname in /etc/rc.conf each time: https://github.com/cbsd/cbsd/blob/develop/sudoexec/jstart#L693-L695

Most likely it is wrong for me, because the user may want to use an arbitrary hostname ( and do not disturb the system administrator for this ).

if we talk about the original problem, we must add something like:
```
modify_host_hostname()
{
if [ ${applytpl} -eq 1 -a "${ver}" != "empty" ]; then
	${SYSRC_CMD} -qf ${data}/etc/rc.conf hostname="${host_hostname}" >/dev/null
fi
}
```
into https://github.com/cbsd/cbsd/blob/develop/jailctl/jset 
(hint: keep in mind- the environments can also be Linux containers, without any /etc/rc.conf!)

However, I would prefer to change the logic as follows:

1) Install (if the /etc/rc.conf file exists) hostname= via jail /etc/rc.conf via JCREATE script, one-time
2) remove https://github.com/cbsd/cbsd/blob/develop/sudoexec/jstart#L693-L695 at all.

**Comment by aeifn** [comment]
i will try this weekend (with corresponding tests)
give me ability to assign myself to issue please )

**Comment by aeifn** [comment]
On-the-fly params are set in `jsetup-tui`, but have no effect:

https://github.com/cbsd/cbsd/blob/00055ec17ad094389d963b6e8b274ab1a5e02abe/jailctl/jsetup-tui#L253-L258
