### ISSUE TITLE
permissions for /usr/local/bin/cbsd

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#654]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 13.0-R

CBSD version ( cbsd version ): 13.0.17

Default permissions on /usr/local/bin/cbsd probably should be:
group: cbsd
g: +x

making it possible to run cbsd without sudo as user in group cbsd.

something like:
```
~ ᐅ ls -l /usr/local/bin/cbsd
---x--x---  1 root  cbsd  183920 Oct 28 04:13 /usr/local/bin/cbsd
```

**Comment by olevole** [comment]
Not sure about 0550, but under discussion. Main reasons 0500:

a) multi-node mode: when we do 'cbsd node mode=add', we are performing remote operations through the 'cbsd' user. Since the root user is usually locked out via SSH. 
We tried not to give the entire root privileges to the cbsd user and several scripts are placed in a separate category: /usr/local/cbsd/sudoexec/*   . Also  see /usr/local/etc/sudoers.d/10_cbsd_sudoers

b) some of these scripts are very dangerous because they can perform destructive operations such as: `rm -rf` , 'zfs destroy` and so on. Thus, anyone in 'cbsd' group and 0550 on '/usr/local/bin/cbsd' automatically becomes a dangerous person for the entire host.

c) Thus, the meaning of assigning a cbsd group to some users is not very clear, because in fact they will be root 

Also, the 0500 mode have been adjusted after several posts like this (~2013-2015y): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=186103
