### ISSUE TITLE
CBSD on a laptop (NAT)

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#676]
I'd like to inquire some information regarding the recommended setup when running FreeBSD on a laptop which is bound to get different IP addresses assigned depending on the network it's connected to.

During the initial CBSD setup the user is asked whether NAT should be enabled for jails. Assuming that the jails are supposed to get access to the internet this option needs to be enabled (unless I'm missing something?). The setup script then asks which IP should be used for NAT which gets default-populated with the laptop's current IP address.

However, when bringing the laptop to a different location (network) it will most likely get a different IP which would break the aforementioned NAT setup.

What is the proper way of handling this / setting this up?

**Comment by olevole** [comment]
If my memory serves me, instead of the IP address, you can specify the interface name as `natip`. In this case, `cbsd naton` ( executed every time the server starts ) will take the address that is used on the interface instead of the fixed address.

But if your internet switches using a different interface... - unfortunately, I don't know what magic to use here ;).
You are probably switching internet manually? In the same way, I think you can change CBSD nat, e.g, execute:

```
env NOINTER=1 cbsd natcfg netip_new=[em0|<new IP>]
cbsd naton
```

**Comment by olevole** [comment]
CBSD provides the simplest example for configuring NAT. In difficult cases, you should turn off cbsd nat control  and use your own scripts.

Hope this helps, I'll close it.
