### ISSUE TITLE
Been Running cbsd for about 3 years now - I see hints there is a webui in development.

### ISSUE THREAD

**Issue by cjemorton** [cbsd/cbsd#746]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD Zeus 13.2-RELEASE-p4 FreeBSD 13.2-RELEASE-p4 GENERIC amd64

CBSD version ( cbsd version ): 
sudo cbsd --version
14.0.0

- I have been running cbsd for atleast 3 years now, I see hints that there is a webui in development 
- Is there any updates on that and if so, is there any code available for us to use?

- I really appreciate this wrapper, it's quite intuitive and seems to work very well. I have all my services running in it. A webui would be great, as well as more indepth documentation and tutorials written.

Thanks again for all the hard work you guys do, it is extremely apreciated.

**Comment by olevole** [comment]
Thank you for the feedback. The web interface has existed for a long time (since 2017): https://clonos.convectix.com/
The project is developing in free time (as well as CBSD), open-sourced:  https://github.com/clonos/control-pane
Unfortunately, the interface is still missing as a FreeBSD port - available as a separate distribution, but you can install it on FreeBSD manually.
