### ISSUE TITLE
nc.inventory contents.

### ISSUE THREAD

**Issue by o1crimsor1o** [cbsd/cbsd#770]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD orbit 14.0-RELEASE-p6 FreeBSD 14.0-RELEASE-p6 #0: Tue Mar 26 20:26:20 UTC 2024     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version ( cbsd version ): 
14.0.8

My question is specifically around setting a dns search string on jails, we can already set the nameserver (with jnameserver). 

Which then lead me into trying to find a list of what could possibly go in the nc.inventory file, to see if I could help myself with this question. But here I am. I'm not sure if this is the proper place to ask this tho.

**Comment by olevole** [comment]
~cbsd/nc.inventory file is auto-generated. You can re-configure settings via `cbsd initenv-tui`.

CBSD does not have a separate parameter for a `search`  string in jail. Instead, you can use 'skel' directory as template (and use it in custom your own 'profile' , if you don't use config management systems like Puppet, Chef, SaltStack, Ansible, ReX...

For example, to change /etc/resolv.conf content in default `skel` directory:

```
echo 'search example.com' > /usr/jails/share/FreeBSD-jail-skel/etc/resolv.conf
```
test:
```
# cbsd jcreate jname=test1 runasap=1 pkg_bootstrap=0
# cat ~cbsd/jails-data/test1-data/etc/resolv.conf
search example.com
nameserver 9.9.9.9   # CBSD makeresolv function
nameserver 149.112.112.112   # CBSD makeresolv function
```

or, you can create your jail profile (in **~cbsd/etc/** directory, checkout **~cbsd/etc/defaults/jail-freebsd-XXXX.conf** profiles as example):
```
cat > ~cbsd/etc/jail-freebsd-myprofile.conf <<EOF
jail_profile="myprofile"
default_jailname="myiail"
default_domain="example.com"

emulator="jail"
jail_active="1"

long_description="myjail profile sample"
jailskeldir="\$workdir/share/\${platform}-jail-myprofile-skel"
# you can pre-set any other jail params here, e.g.:
pkg_bootstrap=0
EOF
```

Create 'myjail' skel directory ( **jailskeldir** ):
```
cp -a ~cbsd/share/FreeBSD-jail-skel ~cbsd/share/FreeBSD-jail-myprofile-skel
```

Create your own resolv.conf for myprofile profile in skel dir:
```
 echo 'search cbsd.io' > ~cbsd/share/FreeBSD-jail-myprofile-skel/etc/resolv.conf
```

To test, create a jail with 'myprofile'  profile:
```
#  cbsd jcreate jname=test1 runasap=1 jprofile=myprofile
# cat ~cbsd/jails-data/test1-data/etc/resolv.conf
search cbsd.io
nameserver 9.9.9.9   # CBSD makeresolv function
nameserver 149.112.112.112   # CBSD makeresolv function
```

**Hint**: also, you can set your profile as default globally, e.g.:

```
echo 'default_profile="myprofile"' > ~cbsd/etc/jail-freebsd-default.conf
```

**Hint2**:  If you prefer CBSDfile method  (instead of `cbsd jcreate` or `cbsd jconstruct-tui`), just use the **skel/** directory for these purposes, example: https://github.com/cbsd/cbsdfile-recipes/tree/master/jail/xfce4

**Comment by o1crimsor1o** [comment]
Thank you! The. nc.inventory file. Does this get remade? Like pulled from a DB to be remade? I want to change jnameserver but I noticed after a few days it was back to the old setting. 


PS: love your work!

**Comment by olevole** [comment]
~cbsd/nc.inventory remade every time you run `cbsd initenv`. Just edit `jnameserver` in `cbsd initenv-tui`.

Also, I added ( https://github.com/cbsd/cbsd/commit/e8fa10aacd64325ffa456c078a85b44b470c8b1c ) the ability to manage the /etc/resolv.conf  file per jail via `cbsd jset`  command, but this will be available in the next CBSD release
