### ISSUE TITLE
fstab.local: How do I mount local zfs filesystems?

### ISSUE THREAD

**Issue by ktk** [cbsd/cbsd#775]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD c-3po 14.1-RELEASE-p3 FreeBSD 14.1-RELEASE-p3 GENERIC amd64

CBSD version ( cbsd version ): 14.1.0

I'm trying to mount some zfs volumes into my jail. I have:

```
zroot/storage/data/db                         5.93G   486G   192K  /zroot/storage/data/db
zroot/storage/data/db/backup                   574M   486G   574M  /zroot/storage/data/db/backup
zroot/storage/data/db/data                    5.37G   486G  5.37G  /zroot/storage/data/db/data
zroot/storage/data/db/log                      176K   486G   176K  /zroot/storage/data/db/log
```
And I would like to mount them into the jail `db`, I thought that way:

```
/zroot/storage/data/db/data   /data/db   nullfs rw 0 0
/zroot/storage/data/db/log    /data/log  nullfs rw 0 0
/zroot/storage/data/db/backup /data/backup nullfs rw 0 0
```

But when I start the jail that way I get:

```
# cbsd jstart db
mkdir: /usr/jails/jails/db/data: Read-only file system
mountfstab warning: mountfstab: unable to create mountpoint for nullfs /zroot/storage/data/db/data: /usr/jails/jails/db/data/db
mountfstab warning: mountfstab: read-only location? Skip mount for: /usr/jails/jails/db/data/db
mkdir: /usr/jails/jails/db/data: Read-only file system
mountfstab warning: mountfstab: unable to create mountpoint for nullfs /zroot/storage/data/db/log: /usr/jails/jails/db/data/log
mountfstab warning: mountfstab: read-only location? Skip mount for: /usr/jails/jails/db/data/log
mkdir: /usr/jails/jails/db/data: Read-only file system
mountfstab warning: mountfstab: unable to create mountpoint for nullfs /zroot/storage/data/db/backup: /usr/jails/jails/db/data/backup
mountfstab warning: mountfstab: read-only location? Skip mount for: /usr/jails/jails/db/data/backup
```

I tried several other combinations but no luck so far. What would be the correct way to create this directory structure in the jail itself and mount the zfs filesystems?

I think the problem is that those directories are mounts on their own but I don't understand what I would have to mount instead.

thanks!

**Comment by olevole** [comment]
Check out official docs: https://www.bsdstore.ru/en/13.0.x/wf_jconfig_ssi.html#allow_zfs

1) you must allow ZFS mounts for `db` jail first:
```
cbsd jset allow_zfs=1 jname=db
```

2) Mount points must be exist/created in the jail directory. For this reason you see 'Read-only file system': when you use RO basejail ( `baserw=0` options ), jail's rootfs where you want to mount datasets is in read-only state (mounted via nullfs-overlay FS from ~cbsd/basejail/base_amd64_amd64_X.Y )

Possible solutions:

a) change mount point into RW area, e.g. /usr/local/db instead of /db (or /var/db/XXX ), e.g. _~cbsd/jails-fstab/db/fstab.local_ sample:
```
zroot/storage/data/db/data     /usr/local/data/db     nullfs rw 0 0
zroot/storage/data/db/log      /usr/local/data/log    nullfs rw 0 0
zroot/storage/data/db/backup   /usr/local/data/backup nullfs rw 0 0
```

or
```
zroot/storage/data/db/data     /var/db/data   nullfs rw 0 0
zroot/storage/data/db/log      /var/db/log    nullfs rw 0 0
zroot/storage/data/db/backup   /var/db/backup nullfs rw 0 0
```

b) create mount points in base rootfs manually:
```
mkdir -p ~cbsd/basejail/base_amd64_amd64_X.Y/data/db
mkdir -p ~cbsd/basejail/base_amd64_amd64_X.Y/data/log
mkdir -p ~cbsd/basejail/base_amd64_amd64_X.Y/data/backup
```

where X.Y - base version ( e.g. 14.1 ) of the jail.
This is not a very good solution, because these directories will be present in each container ( who will use this X.Y. base version ).  In addition, you should always remember about this and every time you update the base version (cbsd downloads the official base.txz rootfs image where your directories do not exist ) and/or when installing a new CBSD hoster, you will have to create these directories again.

c) switch jail to baserw=1 mode:
```
cbsd jset baserw=1 jname=db
cbsd jrestart db
```

In this case, you will not use NULLFS RO overlay from ~cbsd/basejail/base_amd64_amd64_X.Y - the CBSD will automatically make a copy of the base files for your container ). 
This method will allow the system to create directories in the root ( /data /). But you will use up disk space ( ~540 MB ) for an independent copy and your base files will be in write mode:
```
% du -sh ~cbsd/basejail/base_amd64_amd64_*
534M    /usr/jails/basejail/base_amd64_amd64_14.1
```

Please reopen if you still have questions
